{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        # \"this test fails\"\n>       assert False\nE       assert False\n\ntest35_allure.py:14: AssertionError"}, "start": 1686725042895, "stop": 1686725042895, "uuid": "954a2f68-bc09-44db-971f-5458b22228fb", "historyId": "8b56d1fef6954b131ff2e5c38490cbd0", "testCaseId": "8b56d1fef6954b131ff2e5c38490cbd0", "fullName": "test35_allure#test_failure", "labels": [{"name": "suite", "value": "test35_allure"}, {"name": "host", "value": "LAPTOP-Q5VATU4G"}, {"name": "thread", "value": "28076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test35_allure"}]}