{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test36_allure_feature.TestLogin object at 0x000001A518B3DE80>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失效\"):\n>           assert \"1\" == 1\nE           AssertionError: assert '1' == 1\n\ntest36_allure_feature.py:33: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1686731595327, "stop": 1686731595327}, {"name": "点击密码", "status": "passed", "start": 1686731595327, "stop": 1686731595328}, {"name": "点击登录之后登录失效", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\喜格\\pycharm\\My_PythonProject\\Test\\test36_allure_feature.py\", line 33, in test_login_failure\n    assert \"1\" == 1\n"}, "start": 1686731595328, "stop": 1686731595328}], "attachments": [{"name": "stdout", "source": "a4535b05-d623-44f1-8064-0d06fd01fb57-attachment.txt", "type": "text/plain"}], "start": 1686731595327, "stop": 1686731595328, "uuid": "700ecbe2-5da0-46a1-97c8-a421986ec61a", "historyId": "79f5732c0b8e55a1293a0b3cd6a540dc", "testCaseId": "79f5732c0b8e55a1293a0b3cd6a540dc", "fullName": "test36_allure_feature.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test36_allure_feature"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-Q5VATU4G"}, {"name": "thread", "value": "15760-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test36_allure_feature"}]}